maintainer        "Matt Maker"
maintainer_email  "info@entropyreductionservices.com"
license           "MIT"
description       "trip's custom workstation recipes"
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           "1.0.0"
supports          "mac_os_x"
depends           "dmg"
depends           "osx"
depends           "pivotal_workstation"
depends           "sprout-osx-apps"
depends           "sprout-osx-settings"
depends           "sprout-osx-base"
depends           "sprout-pivotal"
depends           "homebrew"
