name             'osx-apps-remove'
maintainer       'Trip'
maintainer_email 'trip@monstro.us'
license          'MIT'
description      'Removes/Un-configures osx-apps'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-osx-base'
depends          'dmg'
