maintainer        'Trip'
maintainer_email  'trip@monstro.us'
license           'MIT'
description       'Uses pivotal_workstation to configure an OSX workstation for ruby development'
long_description  'Uses pivotal_workstation to configure an OSX workstation for ruby development'
version           '0.1.0'
supports          'mac_os_x'

#depends           'pivotal_workstation'
#depends           'osx-settings'
#depends           'osx-apps'
